G ← [8 0 4 7 5 3 9 6 1 0 3 0 1 9 0 2 4 0 1 5 0 6 2 4 0 7 8 0 4 2 0 7 5 1 0 6 5 0 8 0 4 0 7 9 0 6 7 3 8 0 9 5 2 0 2 6 5 0 3 7 8 0 9 0 9 0 5 8 0 6 0 2 0 8 1 9 6 0 4 5 0]
E ← ≅⊝.
B ← ≡E
C ← B⍉
D ← ♭≡(≡(E♭)⍉)↯3_3_3_3
A ← ≅[1]⊝
F ← /(|2 ⊂∩!)♭∵⊂∶,⊜□≠,0∶
H ← ⍤"Wrong length!"=25⧻
I ← ⍤"Invalid chars!"=0/+⊂⊃(<@1)(>@9)
&p "What's the secret code?"
J ← I.H.&sc
K ← -@0.J
A⊂⊂⊃⊃B C D↯9_9F K G
?(&p$"That's correct! The flag is TUDCTF{_}!";)(;;&p"That's wrong.")
